name: whoami-devx

services:
  whoami:
    image: traefik/whoami:latest # Whoami image
    container_name: whoami-devx
    depends_on:
      - traefik
    networks:
      - devxnet
    restart: unless-stopped
    labels:
      - traefik.enable=true # Enable Traefik for this service
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`) # Determine the domain name to use for the service
      - traefik.http.routers.whoami.entrypoints=websecure # Determine the entry point to use for the service
      - traefik.http.routers.whoami.tls=true # Enable TLS for the service
      - traefik.http.services.whoami.loadbalancer.server.port=80 # Determine which port from the service to expose through Traefik
      - traefik.http.routers.whoami.service=whoami # Determine what service to use
      - traefik.http.routers.whoami.tls.certresolver=myresolver # Determine the certificate resolver to use
