services:
  n8n:
    image: ${IMAGE_NAME}:${IMAGE_TAG} # N8N image
    container_name: ${SERVICE_NAME}-devx
    restart: unless-stopped
    networks:
      - devxnet
    ports:
      - "${EXTERNAL_PORT}:5678"
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - N8N_HOST=${SERVICE_NAME}.${DOMAIN_NAME}
      - N8N_PORT=${EXTERNAL_PORT}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SERVICE_NAME}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./data:/home/node/.n8n
      - ./local-files:/files
    labels:
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${DOMAIN_NAME}`)
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${EXTERNAL_PORT}
