services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: ${SERVICE_NAME}
    restart: unless-stopped
    networks:
      - devxnet
    ports:
      - "${EXTERNAL_PORT}:5678"
    environment:
      - N8N_HOST=${SERVICE_NAME}.${DOMAIN_NAME}
      - N8N_PORT=${EXTERNAL_PORT}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SERVICE_NAME}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./data:/home/node/.n8n
      - ./local-files:/files
    labels:
      - "traefik.http.routers.n8n.rule=Host(`${SERVICE_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=${EXTERNAL_PORT}"
