services:
  watchtower:
    image: containrrr/watchtower:latest # Watchtower image
    container_name: watchtower-devx
    restart: unless-stopped
    networks:
      - devxnet
    command:
      - --cleanup=true # Cleanup old images
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket
