services:
  portainer:
    image: ${IMAGE_NAME}:${IMAGE_TAG} # Portainer image
    container_name: ${SERVICE_NAME}-devx
    restart: unless-stopped
    networks:
      - devxnet
    ports:
      - "${EXTERNAL_PORT}:8000"
      - "${EXTERNAL_PORT_SSL}:9443"
      - "${EXTERNAL_PORT_WEBUI}:9000" # for http
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true # Enable Traefik for this service
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${DOMAIN_NAME}`) # Determine the domain name to use for the service
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${EXTERNAL_PORT} # Determine which port from the service to expose through Traefik
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure # Determine the entry point to use for the service
      - traefik.http.routers.${SERVICE_NAME}.tls=true # Enable TLS for the service
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver # Determine the certificate resolver to use
