services:
  portainer:
    image: portainer/portainer-ce:latest # Portainer image
    container_name: portainer-devx
    restart: unless-stopped
    networks:
      - devxnet
    ports:
      - "8000:8000" # for http
      - "8443:8443" # for https
      - "9000:9000" # for webui
    environment:
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true # Enable Traefik for this service
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`) # Determine the domain name to use for the service
      - traefik.http.services.portainer.loadbalancer.server.port=9000 # Determine which port from the service to expose through Traefik
      - traefik.http.routers.portainer.entrypoints=websecure # Determine the entry point to use for the service
      - traefik.http.routers.portainer.tls=true # Enable TLS for the service
      - traefik.http.routers.portainer.tls.certresolver=myresolver # Determine the certificate resolver to use
