name: verdaccio-devx

services:
  verdaccio:
    image: verdaccio/verdaccio:latest # Verdaccio image
    container_name: verdaccio-devx
    volumes:
      - ./conf:/app/conf
      - ./data:/app/storage
    environment:
      - VERDACCIO_PASSWD_FILE=/app/conf/.htpasswd
      - VERDACCIO_PLUGINS=verdaccio-htpasswd-plugin-config.yaml
      - TZ=${GENERIC_TIMEZONE}
    ports:
      - "4873:4873" # HTTP port
    networks:
      - devxnet
    restart: unless-stopped
    labels:
      - traefik.enable=true # Enable Traefik for this service
      - traefik.http.routers.verdaccio.rule=Host(`verdaccio.${DOMAIN_NAME}`) # Determine the domain name to use for the service
      - traefik.http.services.verdaccio.loadbalancer.server.port=4873 # Determine which port from the service to expose through Traefik
      - traefik.http.routers.verdaccio.entryPoints=websecure # Determine the entry point to use for the service
      - traefik.http.routers.verdaccio.tls=true # Enable TLS for the service
      - traefik.http.routers.verdaccio.tls.certresolver=myresolver
